### ISSUE TITLE
New password presentation is easy to miss

### ISSUE THREAD

**Issue by MichaelArestad** [georgestephanis/application-passwords#12]
It's pretty subtle compared to the table and could be more obvious. It might be worth presenting it in a modal accompanied by help text ("spaces don't matter, etc").

**Comment by JeffMatson** [comment]
Solid idea.  I like how cPanel does it on generated passwords with a checkbox confirming you've copied the password.  Do you want to handle this, or shall I?

**Comment by kjbenk** [comment]
I can write up PR for this :)

**Comment by kjbenk** [comment]
Is there some sort of modal example I can work off of?  Or do you want me to use my creative spirit :)

**Comment by JeffMatson** [comment]
Merged
