### ISSUE TITLE
Prevent Passwords with same name?

### ISSUE THREAD

**Issue by kjbenk** [georgestephanis/application-passwords#16]
Currently it is possible to create multiple passwords with the same name.  Should we either:

1. Check if the password name has already been taken before adding it.  If so then we can show an error message.
2. Show the ID of each password next to the name so that there is a way to distinguish each password from each other.  I know that the passwords are stored as a simple array within the user meta so there will be IDs like 0 and also the IDs will be dynamic.
3. Do nothing :)

Let me know your thoughts.

**Comment by JeffMatson** [comment]
I say to show an error stating that the name already exists.

**Comment by kjbenk** [comment]
@georgestephanis and I have come to the conclusion to follow protocol described within this https://github.com/georgestephanis/application-passwords/pull/24#issuecomment-182090778.  I will be creating a PR for this soon :)

**Comment by kjbenk** [comment]
I spent a little bit on time on this and here is my conclusion.  The short answer is that its not that simple :) and the long answer is below.

If we are going to go with the direction laid out in this https://github.com/georgestephanis/application-passwords/pull/24#issuecomment-182090778 then we will need to track all of the duplicates.

Essentially when we get all the passwords we are adding a new element to each password array called `['duplicates']` and we set its value equal to 0.  Then we iterate through the all the passwords and set each passwords `['duplicates']` value equal to the current running tally of duplicates for that password name.  This way when we display the passwords we can check to see if the `['duplicates']` element in each password is greater than 0 and if yes then append that number to the password's display name.

This might sound good but it can create some confusion for the user.  Lets say we have three passwords named the same thing "password".  The table would then have "password", "password (1)" and "password(2)".  If I then revoke "password (1)" then the table would list out the two passwords as "password" and "password (1)".  This is confusing since the new "password (1)" is actually the "password (2)" from before.

So after thinking about this I understand now why @georgestephanis wants to just leave as is since it will decrease complexity and confusion for the user.  Maybe the best option is to just document that passwords names are only for administrative purposes and they do not affect authentication.

@JeffMatson and @georgestephanis thoughts?

**Comment by georgestephanis** [comment]
I'd naturally prefer to leave it as-is and avoid further complexity.

That being said, if we do need to add it, I'd suggest basically doing a regex something like ...

```
if ( preg_match( '/' . preg_quote( trim( $new_name ) ) . '( \([\d]+\))?/', $existing_name, $matches ) ) {
    // something
}
```

Basically regexing out any matches on just the name, or the name plus ` (#)` -- and capturing the number, then just appending 1 + the max of the found numbers to the new one.

That way, if there is:

```
thing
thing (1)
thing (4)
```

(with things 2 and 3 having been revoked), the new one would be 1 + 4, or `thing (5)`

if that makes sense?

But yeah, I'm totally fine leaving the names as just convenient labels that can be duplicates.  Especially as they're fleshed out with creation and usage data in the other columns.

**Comment by kjbenk** [comment]
I like your idea, but at that rate we are basically creating an autointcrementor and I rather just use the `umeta_id` as the ID for each password since it will always be unique.

> But yeah, I'm totally fine leaving the names as just convenient labels that can be duplicates. Especially as they're fleshed out with creation and usage data in the other columns.

I can go either way on this one, but I do think this should be very simple and it appears as though keeping track of duplicate password names and append strings is just not as simple as either:

1. Do nothing :) :+1:
2. Append the `umeta_id` to the end of all passwords, or add it as a new column within the passwords list table :+1: :+1:

**Comment by georgestephanis** [comment]
umeta_id won't work, as they're stored as a big array in one meta entry.

Besides, we don't care about uniqueness code-wise, this is just for potentially simpler time with user comprehension.

**Comment by kjbenk** [comment]
> umeta_id won't work, as they're stored as a big array in one meta entry.

Yes you are 100% correct, I forgot that we were storing the passwords this way.

> Besides, we don't care about uniqueness code-wise, this is just for potentially simpler time with user comprehension.

I agree as well which leads me to believe that just adding documentation on the matter might be the easily and best solution.

Let me know what your final thoughts are so that we can close this task out and move forward :)

**Comment by georgestephanis** [comment]
My thoughts are that we should do nothing.  If they create duplicate names, that's their prerogative.

**Comment by kjbenk** [comment]
> My thoughts are that we should do nothing. If they create duplicate names, that's their prerogative.

Would you be opposed to adding some extra documentation somewhere to state that "password names are for administrative purposes only and duplicate names are allowed"?  I agree that should do nothing code wise but I also think that we should at least add some documentation.

**Comment by georgestephanis** [comment]
Why do we need to declare that?  In the absence of notification, they either:

1) Assume they can't do duplicate names -- no big deal, that's fine.
2) Assume they can -- which is also fine.

I don't see the concern that we need to warn them about.

**Comment by kjbenk** [comment]
I think that simply adding a single sentence to at least describe the purpose of a password name would do nothing but help the user understand how it is used, which allows them to not assume (you know what people say about assuming).

My original thought was maybe to modify the current Add New password textfield and button to look more like a setting, to keep the consistency of all textfields above.  Here is a screenshot of what I had in mind.

![Password Names](https://cldup.com/lfeoDdBwRw.png)

**Comment by JeffMatson** [comment]
I agree with this method.
