### ISSUE TITLE
File Restructuring

### ISSUE THREAD

**Issue by JeffMatson** [georgestephanis/application-passwords#20]
Looks like we're starting to add various files now.  Time for some restructuring.

Thinking:

application-passwords.php
readme.txt
readme.md
assets/screenshot-1.png
assets/screenshot-2.png
includes/classes/class.application-passwords.php
includes/classes/class.application-passwords-list-table.php
includes/css/application-passwords.css
includes/js/application-passwords.js

We might as well get ahead of this before it becomes more work than it's worth.

What's everyone think?  If there aren't any objections, I'll get started.

**Comment by kjbenk** [comment]
That sounds great.

**Comment by kjbenk** [comment]
@JeffMatson I added a PR for this but my structure was not the same as yours.  I normally only like to use /includes for external resources so instead I just kept /css /js and /classes in the root.  I hope this is okay :)

**Comment by georgestephanis** [comment]
We're not getting that complicated, so I'm in favor of keeping it relatively simple, even if it's somewhat messy, for easier understanding on the part of new contributors and less digging to find files.
