### ISSUE TITLE
Passwords Table: Should a password be prepended or appended after creation.

### ISSUE THREAD

**Issue by kjbenk** [georgestephanis/application-passwords#28]
Currently all new passwords are prepended to the passwords table upon creation, but when the table is viewed after a user refreshes the page the newest passwords appear at the bottom.

I believe this is an inconsistency within the UX and I propose two solutions:

1. Append a newly created password instead of prepending it to keep with the password order consistency
2. Order the passwords from newest to oldest to keep with the consistency of where new passwords are added to the table

@georgestephanis let me know your thoughts :)

**Comment by georgestephanis** [comment]
I'd prefer #2, personally.  If the list gets a bit long, it'd probably be easier to see the new one if it always goes on the top.

**Comment by kjbenk** [comment]
Ok I say that we go with option two and see how that looks.

**Comment by kjbenk** [comment]
PR was just merged I am now closing the issue.
