### ISSUE TITLE
Brief design description in readme

### ISSUE THREAD

**Issue by ericandrewlewis** [georgestephanis/application-passwords#37]
Would be cool to see a brief design description high up in the readme. This is a good start in the Description section:

> With Application Passwords you are able to authenticate a user without providing that user's password directly, instead you will use a base64 encoded string of their username and a new application password.

Can we add to that with a description of how clients use this for auth?

**Comment by georgestephanis** [comment]
@ericandrewlewis I'm not sure if this is before or after we added all the usage examples -- is this still relevant, and if so, what would you like to see added?

**Comment by ericandrewlewis** [comment]
I think this was resolved sometime in the interim — closing this out
