### ISSUE TITLE
Javascript errors on site

### ISSUE THREAD

**Issue by joneslloyd** [georgestephanis/application-passwords#43]
When I try to add a key or revoke one, I get the following console errors:

`DELETE https://mysite.com/wp-json/2fa/v1/application-passwords/1/c94e996d441c 403 ()    load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,zxcvbn-async,underscore,wp-util,backbo…:5`

`POST https://mysite.com/wp-json/2fa/v1/application-passwords/1/add 403 ()     load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,zxcvbn-async,underscore,wp-util,backbo…:5`

**Comment by georgestephanis** [comment]
Are you still seeing this issue?

**Comment by joneslloyd** [comment]
I actually stopped using application-passwords shortly after the above error because we were creating something with a pretty quick turnaround and there were a few other ways of going about our issue.

Thanks for checking back with me though :)
