### ISSUE TITLE
Conflict with iThemes Security Pro

### ISSUE THREAD

**Issue by cgrymala** [georgestephanis/application-passwords#45]
I'll report this to the iThemes team, as well, but there's a naming conflict between the two plugins.

It appears that both your plugin and iThemes Security Pro define classes named `Application_Passwords`, so you can't have both plugins active at the same time. I haven't checked to see if the free version of iThemes Security conflicts with this plugin or not. Thanks.

**Comment by aaroncampbell** [comment]
Hey @cgrymala, there's a decent amount of shared code between the original [Two Factor Auth plugin](https://github.com/georgestephanis/two-factor) (back when this was part of it), and the two factor functionality in iThemes Security Pro (which isn't in the free version). Some of our code went into that, and some of that code came back into our codebase. The purpose was to make switching from one to the other easy, avoiding any kind of lock-in.

The functionality of this plugin exists in iThemes Security Pro, so it shouldn't be necessary (or recommended) to run both. It also shouldn't have any conflict with our free plugin, which you could certainly augment by using this.

Having said that, I'll add this to our list as something to look into to try to avoid any possible fatals, but it will need to be looked at at some point after our upcoming release.

**Comment by georgestephanis** [comment]
@aaroncampbell Who picked up the plugin after you left?  Trying to see if this ever got resolved and I can close this out.

**Comment by aaroncampbell** [comment]
That would be Chris Jean.

**Comment by georgestephanis** [comment]
@cgrymala Did you ever hear back from the iThemes folks about this?

**Comment by cgrymala** [comment]
Sorry for not getting back to you. I was trying to verify. 

Just to close the loop on this, yes, iThemes took care of this, so there is no longer a conflict. I apologize in advance if replying re-opens this issue, but I wanted to make sure I closed the loop.
