### ISSUE TITLE
Access Denied for non-admin users

### ISSUE THREAD

**Issue by michael-browne** [georgestephanis/application-passwords#50]
I have a user with a custom user role I would like to give an application password, but when creating a new password on the profile screen I get an "Access Denied" error message returned when I check the developer console. (Although the form simply stays grayed-out, with no response)

Is there a particular user capability that is required to add a password?
Is it possible to allow Subscribers or other users to create an application password?

**Comment by georgestephanis** [comment]
The only capability that should be required is `edit_user` with their own user id -- https://github.com/georgestephanis/application-passwords/blob/master/class.application-passwords.php#L219-L233 -- Can you get me some sample code that I can use to attempt to duplicate the custom role and debug the issue?
