### ISSUE TITLE
Simpler password..??

### ISSUE THREAD

**Issue by planetcrypton** [georgestephanis/application-passwords#53]
Hi, this plugin does exactly what I need for my purpose, let users download some settings to a mobile app (which the app keeps until the user decides to reset them). But I know that entering this type of passwords is going spoil the fun and eventually kill it :)
I know that security should never be underestimated, but is there a way to make the created passwords a little less complicated?

**Comment by georgestephanis** [comment]
The password is as complicated as it is to achieve the required level of entropy to make brute force attacks against it out of the realm of consideration.

However, I hope that the fact that the password only needs to be entered once, as well as #39 (which adds in an authentication flow that will redirect the password back to the requesting website [or potentially app with a custom url scheme] ) should help to mitigate your concerns.
