### ISSUE TITLE
Question for George

### ISSUE THREAD

**Issue by topdown** [georgestephanis/application-passwords#54]
@georgestephanis I was looking through your pull request code and learned all kinds of things, Thanks for that..
But, it also created a question.
Is there benefit to doing nonce the way you did in 
https://github.com/georgestephanis/application-passwords/pull/39/files#diff-a67f6a9179c10f23f65eba957c929506R25
Line 25 of the auth-app.js

Over the typical form nonce and passing the nonce with the data?

If I am reading the code correctly its making an ajax request to check the nonce before posting the data. Correct?

**Comment by georgestephanis** [comment]
That's how the Core REST API works for cookie-based authenticated requests.  You need to include a nonce to prevent CSRF attacks.

http://v2.wp-api.org/guide/authentication/#cookie-authentication
