### ISSUE TITLE
No password appears: how to debug?

### ISSUE THREAD

**Issue by thomasedwards** [georgestephanis/application-passwords#56]
I’m adding a new Application Password, but upon clicking ‘Add New’, the button is disabled and there is no further action. There are no JavaScript errors in the console.

How can I debug this to help figure out where it might be going wrong?

**Comment by wcwhitehead** [comment]
I was having the same problem, except that I was getting two errors in my console for two of the plugin files not being found. What I wound up doing was re-saving the permalink options and that took care of the issue. This plugin works for me as of WP 4.6.1

**Comment by alexey13** [comment]
I have same problem. Getting two errors in console. Saving permalinks not helped.

**Comment by georgestephanis** [comment]
Check your Network tab in the browser debug tools and see if the REST API request that gets fired off processes correctly.
