### ISSUE TITLE
Can't retrieve private post with rest api & Application Passwords?

### ISSUE THREAD

**Issue by amtbnagios** [georgestephanis/application-passwords#59]
Hi!
I installed wordpress 4.7 & Application Passwords plugin( has added a Application Passwords for a admin user)

I can create or update or retrieve posts with rest api (in wordpress 4.7 core)

But if I change a post's status to private, I can't retrieve the post with Application Passwords

Is this rest api limit or Application Passwords limit?

Could some body know & help me ,Thanks a lot!

**Comment by georgestephanis** [comment]
I believe this is an issue with the core REST API, from what I recall?  @kadamwhite -- can you confirm?  Or was that password-protected posts that I'm thinking of there was some debate on?

**Comment by georgestephanis** [comment]
For further context, the user ^^ inquired on the Core REST API repo here previously:

https://github.com/WP-API/WP-API/issues/2991

We don't really differentiate or care what the request is, so I can't imagine how it could be Application Passwords limiting one specific type of post status from being visible.  I'll attempt to duplicate shortly.

**Comment by georgestephanis** [comment]
Closing this out pending further info from the reporter.
