### ISSUE TITLE
period in the way of copy paste

### ISSUE THREAD

**Issue by scarstens** [georgestephanis/application-passwords#6]
The period is part of the structure and gets in the way of the copy and paste.

![image](https://cloud.githubusercontent.com/assets/1483300/12405148/82ed8f20-bdfe-11e5-865e-eefccad5c1ec.png)

**Comment by Ipstenu** [comment]
Maybe...

> Your new password for **android**: `YDJm asc7 tpMM 4Nik`

Would that be better?
