### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by r-a-y** [georgestephanis/application-passwords#65]
Hi,

Nice work!  I came across a small, little bug.

In `readme.md`, you have the following code:

`curl --header "Authorization: Basic ACCESS_TOKEN" -X POST -d "title=New Title" http://LOCALHOST/wp-json/wp/v2/posts/POST_ID}`

The code should be:

`curl --header "Authorization: Basic ACCESS_TOKEN" -X POST -d "title=New Title" http://LOCALHOST/wp-json/wp/v2/posts/POST_ID`

Remove the right curly brace! :)

**Comment by martinjbaker** [comment]
umm this is still there in the current plug-in "Details" section
https://wordpress.org/plugins/application-passwords/#description
