### ISSUE TITLE
401 error Does not work 

### ISSUE THREAD

**Issue by 90navjot** [georgestephanis/application-passwords#67]
I generate password, I try the curl call, I get 401.

{
    "code": "rest_cannot_create",
    "message": "Sorry, you are not allowed to create posts as this user.",
    "data": {
        "status": 401
    }
}

**Comment by eddiewebb** [comment]
Make sure you add the .htaccess changes, you;ll know you need them if you see the warning on the user's page when creating app password.

https://github.com/georgestephanis/application-passwords/wiki/Basic-Authorization-Header----Missing
