### ISSUE TITLE
Improved Composer support by publishing at Packagist.org

### ISSUE THREAD

**Issue by sebask** [georgestephanis/application-passwords#68]
Adding the project to https://packagist.org would improve Composer support since Composer will use the Packagist to find this package. Also this would mean safe upgrading (or not upgrading) to new releases.

You only need to tag a version and submit and publish application-passwords at Packagist. :)

**Comment by georgestephanis** [comment]
PRs are welcome.  Not something I have much time to pursue, but if you're up for the leg work, I'd be happy to thumb stuff up.

**Comment by sebask** [comment]
@georgestephanis Not sure about an PR. I was always under the impression the author of the repo  had to publish it at packagist.org. But I could be wrong.

**Comment by georgestephanis** [comment]
Honestly, I don't have the time or available cognitive load to deal with another integration.  If you'd like to do it, I'll do what I can to let you, but I can't myself.
