### ISSUE TITLE
Support for "pluginless" use of framework

### ISSUE THREAD

**Issue by sebask** [georgestephanis/application-passwords#69]
It would be really nice to be able to use this plugin by downloading it as an dependancy through Composer and including it in a theme.

Currently when I try the latter the plugin doesn't seem to work fully. UI shows up, but i.e. adding keys won't work (just a reload). This is due to the Javascript not being able to load. Since the source is hard coded to the plugins directory, also see https://github.com/georgestephanis/application-passwords/blob/master/class.application-passwords.php#L398.

**Comment by georgestephanis** [comment]
Pull requests are certainly welcome.  This feels like an edge case, and I'm more concerned with core WP coding standards and paradigms.  Still somewhat hoping we get considered for merging into Core as an authentication mechanism.

**Comment by sebask** [comment]
Maybe you're right. Maybe I'll whip up some code and make an PR.
