### ISSUE TITLE
Changed .htaccess file, still get error message

### ISSUE THREAD

**Issue by olive338** [georgestephanis/application-passwords#72]
So I have the common error message in my wordpress admin panel "Due to a potential server misconfiguration, it seems that HTTP Basic Authorization may not work for the REST API on this site: `Authorization` headers are not being sent to WordPress by the web server. You can learn more about this problem, and a possible solution, on our GitHub Wiki."

However, I've already changed my .htaccess files accordingly, and I still see the message in my admin panel. What steps do I take next?

**Comment by micheleriva** [comment]
Same here :(

**Comment by ChristinePowell** [comment]
Yes I am having the same issues, edited the htaccess file and still getting the error message.

**Comment by georgestephanis** [comment]
It could be a permissions issue on the .htaccess file, I'd need to investigate more closely to be sure.

**Comment by georgestephanis** [comment]
>
