### ISSUE TITLE
user defined password generator callbacks

### ISSUE THREAD

**Issue by scones** [georgestephanis/application-passwords#74]
Hello Development-Team,

I'd like to see the feature, where i can set a user defined password generator, as the 5 4-byte chunks are neither secure, nor memorizable.
As tastes go, everyone has one, so i'd prefer to define my own password generator callback, that just returns the password.

**Comment by georgestephanis** [comment]
We've addressed the entropy here: https://github.com/georgestephanis/application-passwords/pull/34 -- the passwords aren't meant to be memorizable -- merely set once in an application and never remembered.  The entropy is sufficiently high to be 'boring' crypto.  https://twitter.com/CiPHPerCoder/status/713592981559881728
