### ISSUE TITLE
frontend shortcode

### ISSUE THREAD

**Issue by mafam1024** [georgestephanis/application-passwords#75]
can i call the functions of creating password from frontend ?
if possible to get shortcode, we can put it in fronted user profile to let user generate password, because we lock login to (/wp-admin) for users out of administrators

**Comment by georgestephanis** [comment]
There's REST API endpoints to create application passwords for the user --

https://github.com/georgestephanis/application-passwords/blob/master/class.application-passwords.php#L89-L99

it should be relatively simple to duplicate the JS code we're using

https://github.com/georgestephanis/application-passwords/blob/master/application-passwords.js

to manage a front-end ui.
