### ISSUE TITLE
Plugin not working in PHP 7

### ISSUE THREAD

**Issue by ckykenken** [georgestephanis/application-passwords#78]
I found that I cannot create application passwords when my site is in PHP 7, I opened up developer's tools, go into console, and it shows error 500. Then I switched back to PHP 5.6, the plugin is working normally. Which PHP module is used by this plugin and why it can't work in PHP 7?

**Comment by thefrosty** [comment]
I see nothing in the code that would warrant a 500 error. I am also running this plugin in a php 7.2 environment without issues.

**Comment by ckykenken** [comment]
It seems to be fixed. I had had that issue when I tried on PHP 7.0.

**Comment by georgestephanis** [comment]
If you can get a php error message, please let me know and I'll investigate deeper.  Closing for now.
