### ISSUE TITLE
Using Postman +Application Passwords to make requests to WordPress REST API 

### ISSUE THREAD

**Issue by noelfernandes** [georgestephanis/application-passwords#79]
Hi All,

I am currently using WordPress v4.9.5 (as stated on the ‘At a glance’ section of the dashboard in the admin panel) hosted on wpengine.com.

Given the above version, I understand that the REST API’s starting from v4.7 onwards are available out of the box and no additional plugins are required. With this, I proceeded to install the Application Passwords plugin to try out the basic authentication. I was able to install the plugin successfully.

I have a user ‘ApiUser’ in WordPress with ‘Admin’ role for which I generated a password that looked like:

eref HgfY HKJH iuot REEt <-(fake password)

I used an [online tool to Base64Encode](https://www.base64encode.org/) the username and newly generated password as follows:
Base64Encoding of ‘ApiUser:erefHgfYHKJHiuotREEt’ results in ‘QXBpVXNlcjplcmVmSGdmWUhLSkhpdW90UkVFdA==’

Using ‘Postman’ I set the Headers as follows:
content-type:application/json
authorization: basic QXBpVXNlcjplcmVmSGdmWUhLSkhpdW90UkVFdA==

and made a simple GET request to:
https://mywebsite.wpengine.com/wp-json/wp/v2/users
https://mywebsite.wpengine.com/wp-json/wp/v2/pages

The response I get is 401 Unauthorized

I was wondering if I am on the right track or if there was something that I was missing out on. Basically I am trying to access site content via the API’s

**Comment by jtammen** [comment]
@noelfernandes Hey, did you try setting the username and application password directly in Postman instead of encoding it? This worked for me!

**Comment by georgestephanis** [comment]
Yup, that.  Also, possibly capitalize the B in Basic?  I could be mistaken on that -- but yeah, ideally setting the username and pass directly is ideal.
