### ISSUE TITLE
Revoke buttons don't work

### ISSUE THREAD

**Issue by jikamens** [georgestephanis/application-passwords#82]
Current version of plugin, current version of WordPress, the buttons for revoking one or all application passwords on the user profile page don't do anything.

**Comment by kasparsd** [comment]
Thanks for reporting the issue @jikamens! Could you please provide detailed steps of how to reproduce the issue? Are there any JS errors in the browser console?

**Comment by jikamens** [comment]
If you'd asked me to do that back in March I could have, but I am no longer using the add-on and do not have time at the moment to debug it further. Have you been unable to reproduce the problem I reported?

**Comment by kasparsd** [comment]
Yes, I'm not able to replicate this. Adding multiple application passwords and clicking "revoke all" removes them as expected:

![application-passwords-deleted](https://user-images.githubusercontent.com/169055/63366877-5f638300-c383-11e9-81b9-6cd7b8437bf4.gif)
