### ISSUE TITLE
Not Tested with WP 5.1.1

### ISSUE THREAD

**Issue by danielkellyio** [georgestephanis/application-passwords#83]
Get a warning when looking at the details of the plugin that it has not been tested with WP 5.1.1. 
![Screen Shot 2019-04-29 at 3 33 46 PM](https://user-images.githubusercontent.com/7635209/56925222-727cdb00-6a94-11e9-8122-389312fbcbe1.png)

**Comment by kasparsd** [comment]
Yeah, this should be a simple fix to bump the version numbers. I'll work on a quick pull request.
